// Auto-generated by scripts/compile.js
import ECONIdentityRegistryArtifact from './artifacts/ECONIdentityRegistry.json';
import ECONEconomicObjectArtifact from './artifacts/ECONEconomicObject.json';
import ECONEscrowArtifact from './artifacts/ECONEscrow.json';
import ECONMarketplaceArtifact from './artifacts/ECONMarketplace.json';
import ECONCreditVaultArtifact from './artifacts/ECONCreditVault.json';

export {
  ECONIdentityRegistryArtifact,
  ECONEconomicObjectArtifact,
  ECONEscrowArtifact,
  ECONMarketplaceArtifact,
  ECONCreditVaultArtifact,
};

export const CONTRACT_NAMES = [
  'ECONIdentityRegistry',
  'ECONEconomicObject',
  'ECONEscrow',
  'ECONMarketplace',
  'ECONCreditVault',
] as const;
