import fs from 'fs';
import path from 'path';
import solc from 'solc';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const contractsDir = path.resolve(__dirname, '../contracts');
const artifactsDir = path.resolve(__dirname, '../src/contracts/artifacts');

if (!fs.existsSync(artifactsDir)) {
  fs.mkdirSync(artifactsDir, { recursive: true });
}

const contractFiles = [
  'ECONIdentityRegistry.sol',
  'ECONEconomicObject.sol',
  'ECONEscrow.sol',
  'ECONMarketplace.sol',
  'ECONCreditVault.sol'
];

console.log('Compiling ECON Smart Contracts with solc...');

const sources = {};
for (const file of contractFiles) {
  const filePath = path.join(contractsDir, file);
  sources[file] = {
    content: fs.readFileSync(filePath, 'utf8')
  };
}

const input = {
  language: 'Solidity',
  sources,
  settings: {
    optimizer: {
      enabled: true,
      runs: 200
    },
    outputSelection: {
      '*': {
        '*': ['abi', 'evm.bytecode', 'evm.deployedBytecode', 'metadata']
      }
    }
  }
};

const output = JSON.parse(solc.compile(JSON.stringify(input)));

let hasErrors = false;
if (output.errors) {
  for (const error of output.errors) {
    if (error.severity === 'error') {
      hasErrors = true;
      console.error('ERROR:', error.formattedMessage);
    } else {
      console.warn('WARNING:', error.formattedMessage);
    }
  }
}

if (hasErrors) {
  console.error('Compilation failed!');
  process.exit(1);
}

const compiledContracts = {};

for (const file of contractFiles) {
  const contractName = file.replace('.sol', '');
  const contract = output.contracts[file][contractName];
  if (!contract) {
    console.error(`Contract ${contractName} not found in output for ${file}`);
    process.exit(1);
  }

  const artifact = {
    contractName,
    sourceName: file,
    abi: contract.abi,
    bytecode: `0x${contract.evm.bytecode.object}`,
    deployedBytecode: `0x${contract.evm.deployedBytecode.object}`,
    metadata: contract.metadata
  };

  const artifactPath = path.join(artifactsDir, `${contractName}.json`);
  fs.writeFileSync(artifactPath, JSON.stringify(artifact, null, 2));
  compiledContracts[contractName] = artifact;
  console.log(`✓ Compiled ${contractName} -> ${artifactPath} (bytecode length: ${artifact.bytecode.length})`);
}

// Generate typed index of ABIs and Bytecodes for frontend and node scripts
const exportContent = `// Auto-generated by scripts/compile.js
${contractFiles.map(file => {
  const name = file.replace('.sol', '');
  return `import ${name}Artifact from './artifacts/${name}.json';`;
}).join('\n')}

export {
${contractFiles.map(file => {
  const name = file.replace('.sol', '');
  return `  ${name}Artifact,`;
}).join('\n')}
};

export const CONTRACT_NAMES = [
${contractFiles.map(file => `  '${file.replace('.sol', '')}',`).join('\n')}
] as const;
`;

fs.writeFileSync(path.resolve(__dirname, '../src/contracts/index.ts'), exportContent);
console.log('✓ Successfully generated src/contracts/index.ts');
console.log('All 5 smart contracts compiled successfully!');
